<Project>
  <PropertyGroup>
    <UnityLangVersion>9.0</UnityLangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <KernelsRuntimeDirectory>$(MSBuildThisFileDirectory)libs/runtime/</KernelsRuntimeDirectory>
  </PropertyGroup>
</Project>
