using System;
using System.Collections.Generic;
using System.Text;

namespace Kernels.Generator.Emit;

internal sealed class SourceWriter
{
    private readonly StringBuilder builder = new();
    private int depth;

    public static string File(string @namespace, Action<SourceWriter> body)
    {
        var writer = new SourceWriter();
        writer.Line("// <auto-generated/>");
        writer.Line("#nullable disable");
        if (@namespace.Length == 0)
        {
            body(writer);
        }
        else
        {
            writer.Open("namespace " + @namespace);
            body(writer);
            writer.Close();
        }

        return writer.builder.ToString();
    }

    public override string ToString() => builder.ToString();

    public SourceWriter Line(string text = "")
    {
        if (text.Length > 0)
        {
            builder.Append(' ', depth * 4).Append(text);
        }

        builder.Append('\n');
        return this;
    }

    public SourceWriter Lines(IEnumerable<string> lines)
    {
        foreach (var line in lines)
        {
            Line(line);
        }

        return this;
    }

    public SourceWriter Directive(string text)
    {
        builder.Append(text).Append('\n');
        return this;
    }

    public SourceWriter Open(string header)
    {
        Line(header);
        Line("{");
        depth++;
        return this;
    }

    public SourceWriter Close()
    {
        depth--;
        return Line("}");
    }
}
